# Generated by Django 5.2.7 on 2025-11-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fleet", "0002_remove_aircraft_tsn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=255)),
                ("part_number", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("date_installed", models.DateTimeField(blank=True, null=True)),
                ("date_removed", models.DateTimeField(blank=True, null=True)),
                ("date_overhauled", models.DateTimeField(blank=True, null=True)),
                ("tsi", models.IntegerField(default=0)),
                ("tso", models.IntegerField(default=0)),
                ("tsn", models.IntegerField(default=0)),
                (
                    "installed_in_ac",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="installed_parts",
                        to="fleet.aircraft",
                    ),
                ),
                (
                    "removed_from_ac",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="removed_parts",
                        to="fleet.aircraft",
                    ),
                ),
            ],
        ),
    ]
