# Generated by Django 5.2.7 on 2025-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "interval_fh",
                    models.PositiveIntegerField(
                        blank=True, help_text="Interval in flight hours", null=True
                    ),
                ),
                (
                    "interval_months",
                    models.PositiveIntegerField(
                        blank=True, help_text="Interval in months", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part", models.CharField(max_length=100)),
                ("part_number", models.CharField(max_length=100)),
                ("serial_number", models.CharField(max_length=100)),
                ("tsn", models.FloatField(help_text="Total hours since new")),
                ("tso", models.FloatField(help_text="Total hours since overhaul")),
                ("tsi", models.FloatField(help_text="Hours since installation")),
                (
                    "removed_from_ac",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "installed_in_ac",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        blank=True,
                        related_name="components",
                        to="components.requirement",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Part",
        ),
    ]
