# Generated by Django 5.2.7 on 2025-11-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_requirement_component_delete_part"),
        ("fleet", "0004_alter_aircraft_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="installed_in_ac",
        ),
        migrations.RemoveField(
            model_name="component",
            name="removed_from_ac",
        ),
        migrations.AlterField(
            model_name="component",
            name="tsi",
            field=models.FloatField(default=0.0, help_text="Time since installation"),
        ),
        migrations.AlterField(
            model_name="component",
            name="tsn",
            field=models.FloatField(default=0.0, help_text="Total hours since new"),
        ),
        migrations.AlterField(
            model_name="component",
            name="tso",
            field=models.FloatField(default=0.0, help_text="Time since overhaul"),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="interval_fh",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="interval_months",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("installed_at", models.DateField()),
                ("removed_at", models.DateField(blank=True, null=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="fleet.aircraft",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="components.component",
                    ),
                ),
            ],
        ),
    ]
