# Generated by Django 5.2.7 on 2025-11-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('date_of_manufacture', models.DateField(blank=True, null=True)),
                ('tfh', models.DecimalField(decimal_places=1, default=0.0, max_digits=8, verbose_name='Total Flight Hours')),
                ('tsn', models.DurationField(blank=True, null=True, verbose_name='Time Since New')),
                ('dow', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Dry Operating Weight (kg)')),
                ('mtw', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Maximum Takeoff Weight (kg)')),
            ],
            options={
                'ordering': ['manufacturer', 'type'],
            },
        ),
    ]
