# Generated by Django 5.2.7 on 2025-11-02 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircraft',
            name='tsn',
        ),
    ]
