# Generated by Django 5.2.7 on 2025-11-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0002_remove_aircraft_tsn"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"ordering": ["registration", "manufacturer", "type"]},
        ),
        migrations.AddField(
            model_name="aircraft",
            name="registration",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
