# Generated by Django 5.2.7 on 2025-11-02 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0003_alter_aircraft_options_aircraft_registration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aircraft",
            options={"ordering": ["registration"]},
        ),
    ]
