# Generated by Django 5.2.8 on 2025-11-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0004_alter_aircraft_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aircraft",
            name="tfh",
            field=models.CharField(
                default="0:00", max_length=10, verbose_name="Total Flight Hours"
            ),
        ),
    ]
